config/routes.rb
Rails.application.routes.draw do
  resources :exrecs do
    resources :exgoods
    resources :exdlvs
  end
  get 'more_info', to: 'people#more'
  get 'delv_info', to: 'delivers#delv'
  get 'more_info_lay', to: 'layrecs#morelay'
  root to:'people#index'
  devise_for :users
  resources :people do
    resources :goods
    resources :pays
    resources :delivers
  end
  resources :layrecs do
    resources :goodlays
    resources :paylays
    resources :deliverlays
  end
end

app/models/person.rb
class Person < ApplicationRecord
  belongs_to :user
  has_many :goods, dependent: :destroy
  has_many :pays, dependent: :destroy
  has_many :delivers, dependent: :destroy
  after_commit :invo_sub
  after_create :capitalize_colmun
  validates :name, presence: true
  validates :phone, presence: true
  validates :email, presence: true
  validates :address, presence: true
  validates :city, presence: true
  validates :state, presence: true
  validates :zip, presence: true
  private
  def capitalize_colmun
    self.update_columns(financ_com: self.financ_com.capitalize)
  end
  def invo_sub
    invo_sub = 0
    invo_tax = 0
    invo_total = 0
    invo_profit = 0
    invo_margin = 0
    invo_delv = 0
    invo_dis = 0
    invo_fee = 0
    self.goods.each do |itm|
      invo_sub += itm.qny * itm.price
    end
    invo_sub
    begin
      self.update_columns(sub_total: invo_sub)
      invo_tax = invo_sub * 10.25 / 100
      if self.tax_inc
        self.update_columns(tax: invo_tax)
      else
        self.update_columns(tax: 0)
      end
      self.delivers.each do |delv|
        invo_delv += delv.delivery
        invo_dis += delv.discount
        invo_fee += delv.fee
      end
      invo_delv
      self.update_columns(delivery: invo_delv)
      invo_dis
      self.update_columns(discount: invo_dis)
      invo_fee
      self.update_columns(fee: invo_fee)
      invo_total = (invo_sub + invo_tax + invo_delv + invo_fee) - invo_dis
      if self.tax_inc
        self.update_columns(total: invo_total)
      else
        self.update_columns(total: invo_total - invo_tax)
      end
      invo_profit = invo_sub - self.cost
      self.update_columns(profit: invo_profit)
      invo_margin = (invo_profit / invo_sub * 100).round(2)
      self.update_columns(margin: invo_margin)
    rescue => e
      "Rescued: #{e.inspect}"
    end
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: [:show, :edit, :update, :destroy]

  def more
    @people = Person.all
    @goods = Good.all
    @pays = Pay.all
    @delivers = Deliver.all
  end
  def index
    @people = Person.all.order("created_at DESC")
  end
  def show
    respond_to do |format|
    format.html
      format.pdf do
        pdf = InvoicePdf.new(@person, view_context)
        send_data pdf.render, filename: "invoice_#{@person.phone}.pdf", type: "application/pdf", disposition: "inline"
      end
    end
  end
  def new
    @person = current_user.people.build
  end
  def edit
  end
  def create
    @person = current_user.people.build(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, success: 'Invoice was successfully created.' }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to @person, info: 'Invoice was successfully updated.' }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end
  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to people_url, warning: 'Invoice was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  def set_person
    @person = Person.find(params[:id])
  end
  def person_params
    params.require(:person).permit(:name, :phone, :email, :address, :address2, :city,
      :state, :zip, :sub_total, :tax, :total, :slae_rep, :profit, :margin, :cost, :delivery,
      :fee, :discount, :finance, :tax_inc, :user_id, :financ_com)
  end
end

app/helpers/people_helper.rb
module PeopleHelper
  def months_of_the_year
   ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December']
  end
  def sub_totls
    sub_totls = 0
    @person.goods.each do |comt|
      sub_totls += comt.qny * comt.price
    end
    sub_totls
  end
  def tax_calc
    tax_calc = sub_totls * 10.25 / 100
  end
  def tot_pay
    tot_pay = 0
    @person.pays.each do |pay|
      tot_pay += pay.amount
    end
    tot_pay
  end
  def inv_dicount
    inv_dicount = 0
    @person.delivers.each do |delv|
      inv_dicount += delv.discount
    end
     inv_dicount ||= "00.00"
  end
  def inv_delivery
    inv_delivery = 0
    @person.delivers.each do |delv|
      inv_delivery += delv.delivery
    end
    inv_delivery ||= "00.00"
  end
  def inv_fee
      inv_fee = 0
    @person.delivers.each do |delv|
       inv_fee = delv.fee
    end
    inv_fee ||= "00.00"
  end
  def totall
    totll = (sub_totls + inv_fee + inv_delivery) - inv_dicount
  end
  # toal due for tax purchase
  def total_reg
    total_reg = tax_calc + sub_totls + inv_fee + inv_delivery - inv_dicount
  end
  # total after subtract total due from total payments
  def tot_reg
    tot_reg = 0
    tot_reg = (totall - tot_pay ).round(2)
  end

  def tot_reg_tax
    tot = 0
    tot = (total_reg - tot_pay).round(2)
  end
  def total_invoices
    totals = 0
    Person.all.each do |per|
     totals += per.total
    end
    totals
  end
  def total_subs
    total_subs = 0
    Person.all.each do |per|
     total_subs += per.sub_total
    end
    total_subs
  end
  def total_taxs
    total_taxs = 0
    Person.all.each do |per|
     total_taxs += per.tax
    end
    total_taxs
  end
  def total_fees
    total_fees = 0
    Person.all.each do |per|
     total_fees += per.fee
    end
    total_fees
  end
  def total_discounts
    total_discounts = 0
    Person.all.each do |per|
     total_discounts += per.discount
    end
    total_discounts
  end
  def total_costs
    total_costs = 0
    Person.all.each do |per|
     total_costs += per.cost
    end
    total_costs
  end
  def total_delvs
    total_delvs = 0
    Person.all.each do |per|
     total_delvs += per.delivery
    end
    total_delvs
  end
  def total_profits
    total_profits = 0
    Person.all.each do |per|
     total_profits += per.profit
    end
    total_profits
  end
end

app/views/people/_fin_tax.html.erb
<center>
  <% if current_user  && current_user.admin? %>
    <div class='container'>
      <table class='table table-hover table-striped'>
        <thead class='table-dark'>
          <tr>
            <th>Total Invoce</th>
            <th>Sub Total</th>
            <th>Tax</th>
            <th>Discount</th>
            <th>Delivery</th>
            <th>Fee</th>
            <th>Cost</th>
            <th>Profit</th>
            <th>Margin</th>
          </tr>
        </thead>

        <tbody>
            <tr>
              <td><%= number_to_currency @person.total %></td>
                <td><%= number_to_currency @person.sub_total %></td>
                <td><%= number_to_currency @person.tax %></td>
                <td><%= number_to_currency @person.discount %></td>
                <td><%= number_to_currency @person.delivery %></td>
                <td><%= number_to_currency @person.fee %></td>
                <td><%= number_to_currency @person.cost %></td>
                <td><%= number_to_currency @person.profit  %></td>
                <td><%= ( @person.profit / @person.sub_total * 100).round(2) %> %</td>
            </tr>
        </tbody>
    </table>
    </div>
  <% end %>

  <div class="container" style="width: 93%">
    <button type="button" class="btn btn-warning btn-lg btn-block">Purchase Details!</button>
  </div>
  <table class='table table-hover table-striped' style="width: 90%;">
      <thead class='table-dark'>
        <tr>
          <th>QNTY</th>
          <th>Item</th>
          <th>Price</th>
          <th>Description</th>
          <th>Subtotal</th>
          <th>Tax</th>
          <th>Total</th>
          <th>Action</th>
        </tr>
      </thead>

      <tbody>
        <%  %>
        <% @person.goods.each do |itm| %>
          <tr>
            <td><%= itm.qny %></td>
            <td><%= number_to_currency itm.price %></td>
            <td><%= itm.item %></td>
            <td><%= itm.description %></td>
            <% sub_totl = itm.price * itm.qny %>
            <td><%= number_to_currency sub_totl %></td>
            <% tax_itm = itm.price * itm.qny * 10.25 / 100%>
            <td><%= number_to_currency tax_itm %></td>
            <td><%= number_to_currency sub_totl + tax_itm  %></td>
            <td><%= link_to (image_tag('delx.png',  height: '40px', width: '40px')), [@person, itm], method: :delete, data: { confirm: 'You are about delete this item!' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table><hr><br>
  </center>

<div class="container">
  <div class="row">
    <div class="col-sm">
      <button type="button" class="btn btn-success btn-lg btn-block">Delivery Details</button><br>
      <% @person.delivers.each do |delv| %>
        Delivert Fee: <%= number_to_currency delv.delivery %><br>
        Fee: <%= number_to_currency delv.fee %>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <td><%= link_to (image_tag('delx.png',  height: '60px', width: '60px')), [@person, delv], method: :delete, data: { confirm: 'You are about delete this item!' } %></td><br>
        Discount: <%= number_to_currency delv.discount %>
        <hr>
      <% end %>
    </div>
    <div class="col-sm">
      <font size="4" color="red"><%= number_to_currency sub_totls %> Items Subtotal</font><br>
      <font size="4" color="red"><%= number_to_currency tax_calc %> Invoice TAX</font><br>
      <font size="4" color="red"><%= number_to_currency inv_delivery %> Delivery Fee</font><br>
      <font size="4" color="red"><%= number_to_currency inv_fee   %> Fee If Apply  -</font><br>
      <font size="4" color="blue"><%= number_to_currency inv_dicount  %> Discount If Apply</font><br>
      <hr>
      <font size="5" color="red"><%= number_to_currency totall + tax_calc %> Invoice Due!</font><br>
      <hr>
      <font size="6" color="green"> <%= number_to_currency totall + tax_calc %> Paid by: <%= @person.financ_com.titleize %> </font>

    </div>
  </div>
</div><br>


<a href="#" id="show_items">
  <button type="button" class="btn btn-info btn-lg btn-block"><h3>1- Click to Add Items Details!</h3></button><br>
</a>
<div id="items" class="hidden">
  <div class="container" style= 'background-color: #F0FFFF'>
    <%= form_for [@person, @person.goods.build] do |f| %>
      <div class="container">
        <div class="row">
          <div class="col-sm">
            <%= f.label :qny %><br>
            <%= f.select :qny, [0,1,2,3,4,5,6,7,8,9,10,11,12] %>
          </div>
          <div class="col-sm">
          <%= f.label :item %>
            <%= f.text_field :item  %>
          </div>
          <div class="col-sm">
            <%= f.label :description %>
            <%= f.text_field :description %>
          </div>
          <div class="col-sm">
            <%= f.label :price %>
            <%= f.text_field :price %>
          </div>
          <div class="col-sm">
          <%= f.label :vendor %><br>
            <%= f.text_field :vendor%>
          </div>
        </div>

          <div class="col-sm"><br>
            <div class="actions">
              <button class="btn btn-success btn-lg btn-block " type="submit"><h3> Click here to ADD New Item!</h3></button>
            </div><br>
          </div>
        </div>
      </div>
    <% end %>
  </div><br>

<a href="#" id="show_delivery">
  <button type="button" class="btn btn-info btn-lg btn-block"><h3>2- Click to Add Delivery Details!</h3></button>
</a><br>
<div id="delivery" class="hidden">
  <div class="container" style= 'background-color: #F0FFFF'><br>
    <%= form_for [@person, @person.delivers.build] do |f| %>
      <div class="row">
        <div class="col">
          <div class="col-sm">
            Delivery Fee: <%= f.text_field :delivery %>
          </div>
        </div>
        <div class="col">
          <div class="col-sm">
            Fee If Apply: <%= f.text_field :fee%>
          </div>
        </div>
        <div class="col">
          <div class="col-sm">
            Discount If Apply: <%= f.text_field :discount %>
          </div>
        </div>
        <div class="col">
          <div class="col-sm">
            Delivery Date: <%= f.date_select :delivery_date%>
          </div>
        </div>
      </div>
      <div class="col-sm"><br>
        <div class="actions">
          <button class="btn btn-success btn-lg btn-block " type="submit"><h3>Click here to ADD Delivery  Details and Discount if Apply!</h3></button>
        </div><br>
      </div>
    <% end %>
  </div><br>
</div><br><br>

app/views/people/_finance.html.erb
<center>
  <% if current_user  && current_user.admin? %>
    <div class='container'>
      <table class='table table-hover table-striped'>
        <thead class='table-dark'>
          <tr>
            <th>Total Invoce</th>
            <th>Sub Total</th>
            <th>Delivery</th>
            <th>Fee</th>
            <th>Discount</th>
            <th>Cost</th>
            <th>Profit</th>
            <th>Margin</th>
          </tr>
        </thead>

        <tbody>
            <tr>
              <td><%= number_to_currency @person.total %></td>
                <td><%= number_to_currency @person.sub_total %></td>
                <td><%= number_to_currency @person.delivery %></td>
                <td><%= number_to_currency @person.fee %></td>
                <td><%= number_to_currency @person.discount %></td>
                <td><%= number_to_currency @person.cost %></td>
                <td><%= number_to_currency @person.profit %></td>
                <td><%= ( @person.profit / @person.sub_total * 100).round(2) %> %</td>
            </tr>
        </tbody>
    </table>
    </div>
  <% end %>

  <div class="container" style="width: 93%">
    <button type="button" class="btn btn-warning btn-lg btn-block">Purchase Details!</button>
  </div>
  <table class='table table-hover table-striped' style="width: 90%;">
    <thead class='table-dark'>
      <tr>
        <th>QNTY</th>
        <th>Item</th>
        <th>Price</th>
        <th>Description</th>
        <th>Subtotal</th>
        <th>Total</th>
        <th>Action</th>
      </tr>
    </thead>

    <tbody>
      <%  %>
      <% @person.goods.each do |itm| %>
        <tr>
          <td><%= itm.qny %></td>
          <td><%= number_to_currency itm.price %></td>
          <td><%= itm.item %></td>
          <td><%= itm.description %></td>
          <% sub_totl = itm.price * itm.qny %>
          <td><%= number_to_currency sub_totl %></td>
          <% tax_itm = itm.price * itm.qny * 10.25 / 100%>
          <td><%= number_to_currency sub_totl  %></td>
          <td><%= link_to (image_tag('delx.png',  height: '40px', width: '40px')), [@person, itm], method: :delete, data: { confirm: 'You are about delete this item!' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table><hr><br>
</center>


<div class="container">
<div class="row">
  <div class="col-sm">
    <button type="button" class="btn btn-success btn-lg btn-block">Delivery Details</button><br>
    <% @person.delivers.each do |delv| %>
      Delivert Fee: <%= number_to_currency delv.delivery %><br>
      Fee: <%= number_to_currency delv.fee %><br>
      Discount: <%= number_to_currency delv.discount %>&nbsp;&nbsp;&nbsp;&nbsp;
      <td><%= link_to (image_tag('delx.png',  height: '40px', width: '40px')), [@person, delv], method: :delete, data: { confirm: 'You are about delete this item!' } %></td>
      <hr>
    <% end %>
  </div>
  <div class="col-sm">
    <font size="4" color="red"><%= number_to_currency sub_totls %> Items Subtotal</font><br>
    <% if @person.tax == true %>
      <font size="4" color="red"><%= number_to_currency tax_calc %> Invoice TAX</font><br>
    <% end %>
    <font size="4" color="red"><%= number_to_currency inv_delivery %> Delivery Fee</font><br>
    <font size="4" color="red"><%= number_to_currency inv_fee   %> Fee If Apply  -</font><br>
    <font size="4" color="blue"><%= number_to_currency inv_dicount  %> Discount If Apply</font><br>
    <hr>
    <font size="5" color="red"><%= number_to_currency totall  %> Invoice Due!</font><br>
    <hr>
    <font size="6" color="green"> <%= number_to_currency totall  %> Paid by: <%= @person.financ_com.titleize %> </font>
  </div>
</div>
</div><br>

<a href="#" id="show_items">
  <button type="button" class="btn btn-info btn-lg btn-block"><h3>1- Click to Add Items Details!</h3></button><br>
</a>
<div id="items" class="hidden">
  <div class="container" style= 'background-color: #F0FFFF'>
    <%= form_for [@person, @person.goods.build] do |f| %>
      <div class="container">
        <div class="row">
          <div class="col-sm">
            <%= f.label :qny %><br>
            <%= f.select :qny, [0,1,2,3,4,5,6,7,8,9,10,11,12] %>
          </div>
          <div class="col-sm">
          <%= f.label :item %>
            <%= f.text_field :item %>
          </div>
          <div class="col-sm">
            <%= f.label :description %>
            <%= f.text_field :description %>
          </div>
          <div class="col-sm">
            <%= f.label :price %>
            <%= f.text_field :price %>
          </div>
          <div class="col-sm">
          <%= f.label :vendor %><br>
            <%= f.text_field :vendor  %>
          </div>
        </div>

          <div class="col-sm"><br>
            <div class="actions">
              <button class="btn btn-success btn-lg btn-block " type="submit"><h3> Click here to ADD New Item!</h3></button>
            </div><br>
          </div>
        </div>
      </div>
    <% end %>
  </div><br>

<a href="#" id="show_delivery">
  <button type="button" class="btn btn-info btn-lg btn-block"><h3>2- Click to Add Delivery Details!</h3></button>
</a><br>
<div id="delivery" class="hidden">
  <div class="container" style= 'background-color: #F0FFFF'><br>
    <%= form_for [@person, @person.delivers.build] do |f| %>
      <div class="row">
        <div class="col">
          <div class="col-sm">
            Delivery Fee: <%= f.text_field :delivery %>
          </div>
        </div>
        <div class="col">
          <div class="col-sm">
            Fee If Apply: <%= f.text_field :fee%>
          </div>
        </div>
        <div class="col">
          <div class="col-sm">
            Discoint If Apply: <%= f.text_field :discount %>
          </div>
        </div>

        <div class="col">
          <div class="col-sm">
            Delivery Date: <%= f.date_select :delivery_date %>
          </div>
        </div>


      </div>
      <div class="col-sm"><br>
        <div class="actions">
          <button class="btn btn-success btn-lg btn-block " type="submit"><h3>Click here to ADD Delivery  Details and Discount if Apply!</h3></button>
        </div><br>
      </div>
    <% end %>
  </div><br>
</div><br><br>

<br>

app/views/people/_form.html.erb
<%= form_with(model: person, local: true) do |form| %>
  <% if person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
        <% person.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<div class="container" style="background-color: #cceeff;" ><br>
  <div class="row">
    <div class="col-sm">
      <div class="field">
        <%= form.label :name %>
        <%= form.text_field :name, class:'form-control' %>
      </div>

      <div class="field">
        <%= form.label :phone %>
        <%= form.text_field :phone, class:'form-control' %>
      </div>

      <div class="field">
        <%= form.label :email %>
        <%= form.text_field :email, class:'form-control' %>
      </div>
    </div>
    <div class="col-sm">
      <div class="field">
        <%= form.label :address %>
        <%= form.text_field :address, class:'form-control'%>
      </div>

      <div class="field">
        <%= form.label :address2 %>
        <%= form.text_field :address2, class:'form-control' %>
      </div>

      <div class="field">
        <%= form.label :city %>
        <%= form.text_field :city, class:'form-control' %>
      </div>
    </div>
    <div class="col-sm">
      <div class="field">
        <%= form.label :zip %>
        <%= form.text_field :zip, class:'form-control' %>
      </div>
      <div class="field">
        <%= form.label :state %>
        <%= form.text_field :state, class:'form-control' %>
      </div><br>

      <div class="field">
        Sale Rep: <%= form.select :slae_rep,[current_user.username] %>
      </div>
    </div>
  </div><br>
</div><br>
<!-- tax, finance if include  -->
<div class="container">
  <div class="row">
    <div class="col-sm">
      <button type="button" class="btn btn-success btn-lg btn-block">
        Please Click to include TAX!&nbsp;&nbsp; <%= form.check_box :tax_inc %>
      </button>
    </div>
    <div class="col-sm">
      <button type="button" class="btn btn-warning btn-lg btn-block">
        Please Click if Finance!&nbsp;&nbsp; <%= form.check_box :finance %>&nbsp;&nbsp;
        <%= form.text_field :financ_com, placeholder: "Finance company " %>
      </button>
    </div>
  </div>
</div><br>

  <% if current_user  && current_user.admin? %>
    <div class="field">
      <font size="5" color="red">Please Update the Actual Cost for this Invoice!</font><br>
      <%= form.text_field :cost, class:'form-control' %>
    </div><br>
  <% end %>

  <div class="actions">
    <button class="btn btn-info btn-lg btn-block" type="submit"><h2>Proceed to Step #2 to Add Sales Details! </h2></button>
  </div>
<% end %>

app/views/people/edit.html.erb
<br>
<button type="button" class="btn btn-primary btn-lg btn-block">Edit Customer Info </button>

<%= render 'form', person: @person %>

<%= link_to 'Show', @person, :class => "btn btn-outline-success" %>
<%= link_to 'Back', people_path, :class => "btn btn-outline-success" %>

app/views/people/index.html.erb
<div class="row">
  <div class="col-sm">
    <%= link_to 'All Sample Invoices', exrecs_path, :class => "btn btn-outline-success btn-lg btn-block" %>
  </div>
  <div class="col-sm">
    <%= link_to 'New Sample Invoice', new_exrec_path, :class => "btn btn-outline-danger btn-lg btn-block"  %>
  </div>
  <div class="col-sm">
    <%= link_to 'New Layway Purchase', new_layrec_path, :class => "btn btn-outline-warning btn-lg btn-block"  %>
  </div>
  <div class="col-sm">
    <%= link_to 'All Layaway Invoices', layrecs_path, :class => "btn btn-outline-info btn-lg btn-block" %>
  </div>
</div><br>
<%= link_to 'New Purchase Please Click to Start!', new_person_path, :class => "btn btn-outline-success btn-lg btn-block" %><br>

<button type="button" class="btn btn-info btn-lg btn-block">
  <h3>All Invoices!</h3>
</button>
<center>
  <table id="person" class="table table-striped table-bordered" style="width: 1000px;">
  <thead class="table-success">
    <tr>
      <th>qty</th>
      <th>Name</th>
      <th>Phone</th>
      <th>Date</th>
      <% if current_user  && current_user.admin? %>
        <th>Action</th>
        <th>Action</th>
      <% end %>
    </tr>
  </thead>

  <tbody>
    <% @people.each do |person| %>
      <tr>
        <td><%= person.id %></td>
        <td><%= link_to person.name, person %></td>
        <td><%= number_to_phone person.phone %></td>
        <td><%= person.created_at.strftime('%m/%d/%Y') %></td>
        <% if current_user  && current_user.admin? %>
          <td><%= link_to 'Edit', edit_person_path(person) %></td>
          <td><%= link_to 'Destroy', person, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
</center>
<br>

app/views/people/new.html.erb
<br>
<button type="button" class="btn btn-primary btn-lg btn-block">New Customer Info </button>

<%= render 'form', person: @person %>

<%= link_to 'Back', people_path, :class => "btn btn-outline-success" %>

app/views/people/show.html.erb
<%= link_to "print Recipt (PDF)", person_path(@person, format: 'pdf'), class:"btn btn-outline-success" %><br><br>
<% if @person.finance == true %>
  <div class="container" style="width: 93%">
    <button type="button" class="btn btn-success btn-lg btn-block">Finance Purchase</button>
  </div>
<% else %>
  <div class="container" style="width: 93%">
    <button type="button" class="btn btn-danger btn-lg btn-block">Reguler Purchase</button>
  </div>
<% end %>
<div class="container" style= 'background-color: #F0FFFF'><br>
  <% if @person.tax_inc == true && @person.finance == true %>
    <%= render 'fin_tax' %>
  <% elsif  @person.finance == true %>
    <%= render 'finance' %>
  <% else %>
    <%= render 'regular' %>
  <% end %>
  <br>
  <% if current_user  && current_user.admin? %>
    <%= link_to 'Edit Customer Information Only!', edit_person_path(@person), :class => "btn btn-danger"  %>
  <% end %>
  <%= link_to 'Back to All Invoices!', people_path, :class => "btn btn-outline-success" %>
</div>