config/routes.rb
Rails.application.routes.draw do
  resources :exrecs do
    resources :exgoods
    resources :exdlvs
  end
  get 'more_info', to: 'people#more'
  get 'delv_info', to: 'delivers#delv'
  get 'more_info_lay', to: 'layrecs#morelay'
  root to:'people#index'
  devise_for :users
  resources :people do
    resources :goods
    resources :pays
    resources :delivers
  end
  resources :layrecs do
    resources :goodlays
    resources :paylays
    resources :deliverlays
  end
end

app/models/layrec.rb
class Layrec < ApplicationRecord
  belongs_to :user
  has_many :goodlays, dependent: :destroy
  has_many :paylays, dependent: :destroy
  has_many :deliverlays, dependent: :destroy
  after_commit :invo_info
  private
  def invo_info
    invo_sub_lay = 0
    invo_tax_lay  = 0
    invo_total_lay  = 0
    invo_profit_lay  = 0
    invo_margin_lay  = 0
    invo_delv_lay  = 0
    invo_dis_lay  = 0
    invo_fee_lay  = 0
    total_payments = 0
    self.goodlays.each do |itm|
      invo_sub_lay  += itm.qny * itm.price
    end
    self.paylays.each do |pay|
      total_payments += pay.amount
    end
    total_payments
    begin
      self.update_columns(tot_pauments: total_payments )
      invo_sub_lay
      self.update_columns(sub_total: invo_sub_lay )
      invo_tax_lay  = invo_sub_lay * 10.25 / 100
      self.update_columns(tax: invo_tax_lay )
      self.deliverlays.each do |delv|
        invo_delv_lay  += delv.delivery
        invo_dis_lay  += delv.discount
        invo_fee_lay  += delv.fee
      end
      invo_delv_lay
      self.update_columns(delivery: invo_delv_lay )
      invo_dis_lay
      self.update_columns(discount: invo_dis_lay )
      invo_fee_lay
      self.update_columns(fee: invo_fee_lay )
      invo_total_lay  = (invo_sub_lay  + invo_tax_lay  + invo_delv_lay  + invo_fee_lay ) - invo_dis_lay
      self.update_columns(total: invo_total_lay )
      invo_profit_lay  = invo_sub_lay  - self.cost
      self.update_columns(profit: invo_profit_lay )
      invo_margin_lay  = (invo_profit_lay  / invo_sub_lay  * 100).round(2)
      self.update_columns(margin: invo_margin_lay )
    rescue => e
      "Rescued: #{e.inspect}"
    end
  end
end

app/controllers/layrecs_controller.rb
class LayrecsController < ApplicationController
  before_action :set_layrec, only: [:show, :edit, :update, :destroy]
  def morelay
    @layrecs = Layrec.all
    @goodlays = Goodlay.all
    @paylays = Paylay.all
    @deliverlays = Deliverlay.all
  end
  def index
    @layrecs = Layrec.all.order("created_at DESC")
  end

  def new
    @layrec = current_user.layrecs.build
  end

  def show
    respond_to do |format|
    format.html
      format.pdf do
        pdf = InvoiceLayPdf.new(@layrec, view_context)
        send_data pdf.render, filename: "invoice_#{@layrec.phone}.pdf", type: "application/pdf", disposition: "inline"
      end
    end
  end

  def edit
  end

  def create
    @layrec = current_user.layrecs.build(layrec_params)

    respond_to do |format|
      if @layrec.save
        format.html { redirect_to @layrec, success: 'Invoice was successfully created.' }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new }
        format.json { render json: @layrec.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @layrec.update(layrec_params)
        format.html { redirect_to @layrec, info: 'Invoice was successfully updated.' }
        format.json { render :show, status: :ok, location: @layrec }
      else
        format.html { render :edit }
        format.json { render json: @layrec.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @layrec.destroy
    respond_to do |format|
      format.html { redirect_to layrec_url, warning: 'Invoice was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  def set_layrec
    @layrec = Layrec.find(params[:id])
  end

  def layrec_params
    params.require(:layrec).permit(:name, :phone, :email, :address, :address2, :city,
      :state, :zip, :sub_total, :tax, :total, :sale_rep, :profit, :margin, :cost,
      :delivery, :fee, :discount, :tax_inc, :tot_pauments, :user_id)
  end
end

app/helpers/layrecs_helper.rb
module LayrecsHelper

  def lay_sub_totls
    lay_sub_totls = 0
    @layrec.goodlays.each do |comt|
      lay_sub_totls += comt.qny * comt.price
    end
    lay_sub_totls
  end
  def lay_tax_calc
    lay_tax_calc = lay_sub_totls * 10.25 / 100
  end
  def lay_tot_pay
    lay_tot_pay = 0
    @layrec.paylays.each do |pay|
      lay_tot_pay += pay.amount
    end
    lay_tot_pay
  end
  def lay_inv_dicount
    lay_inv_dicount = 0
    @layrec.deliverlays.each do |delv|
      lay_inv_dicount += delv.discount
    end
     lay_inv_dicount ||= "00.00"
  end
  def lay_inv_delivery
    lay_inv_delivery = 0
    @layrec.deliverlays.each do |delv|
      lay_inv_delivery += delv.delivery
    end
    lay_inv_delivery ||= "00.00"
  end
  def lay_inv_fee
      lay_inv_fee = 0
    @layrec.deliverlays.each do |delv|
       lay_inv_fee = delv.fee
    end
    lay_inv_fee
  end
  def lay_totall
    lay_totll = lay_sub_totls + lay_inv_fee + lay_inv_delivery - lay_inv_dicount
  end
  def lay_total_reg
    lay_total_reg = lay_tax_calc + lay_sub_totls + lay_inv_fee + lay_inv_delivery - lay_inv_dicount
  end
  def lay_tot_reg
    lay_tot_trg = 0
    lay_tot_trg = (lay_total_reg - lay_tot_pay).round(2)
  end
  def lay_tot
    lay_tot = 0
    lay_tot = (lay_totall  - lay_tot_pay).round(2)
  end
  def lay_total_invoices
    totals = 0
    Layrec.all.each do |per|
     totals += per.total
    end
    totals
  end
  def lay_total_subs
    total_subs = 0
    Layrec.all.each do |per|
     total_subs += per.sub_total
    end
    total_subs
  end
  def lay_total_taxs
    total_taxs = 0
    Layrec.all.each do |per|
     total_taxs += per.tax
    end
    total_taxs
  end
  def lay_total_fees
    total_fees = 0
    Layrec.all.each do |per|
     total_fees += per.fee
    end
    total_fees
  end
  def lay_total_discounts
    total_discounts = 0
    Layrec.all.each do |per|
     total_discounts += per.discount
    end
    total_discounts
  end
  def lay_total_costs
    total_costs = 0
    Layrec.all.each do |per|
     total_costs += per.cost
    end
    total_costs
  end
  def lay_total_delvs
    total_delvs = 0
    Layrec.all.each do |per|
     total_delvs += per.delivery
    end
    total_delvs
  end
  def lay_total_profits
    total_profits = 0
    Layrec.all.each do |per|
     total_profits += per.profit
    end
    total_profits
  end
end

app/views/layrecs/_form.html.erb
<%= form_with(model: layrec, local: true) do |form| %>
  <% if layrec.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(layrec.errors.count, "error") %> prohibited this layrec from being saved:</h2>

      <ul>
        <% layrec.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<div class="container" style="background-color: #cceeff;" ><br>
  <div class="row">
    <div class="col-sm">
      <div class="field">
        <%= form.label :name %>
        <%= form.text_field :name, class:'form-control' %>
      </div>

      <div class="field">
        <%= form.label :phone %>
        <%= form.text_field :phone, class:'form-control' %>
      </div>

      <div class="field">
        <%= form.label :email %>
        <%= form.text_field :email, class:'form-control' %>
      </div>
    </div>
    <div class="col-sm">
      <div class="field">
        <%= form.label :address %>
        <%= form.text_field :address, class:'form-control'%>
      </div>

      <div class="field">
        <%= form.label :address2 %>
        <%= form.text_field :address2, class:'form-control' %>
      </div>

      <div class="field">
        <%= form.label :city %>
        <%= form.text_field :city, class:'form-control' %>
      </div>
    </div>
    <div class="col-sm">
      <div class="field">
        <%= form.label :zip %>
        <%= form.text_field :zip, class:'form-control' %>
      </div>
      <div class="field">
        <%= form.label :state %>
        <%= form.text_field :state, class:'form-control' %>
      </div><br>

      <div class="field">
        Sale Rep: <%= form.select :sale_rep,[current_user.username] %>
      </div>
    </div>
  </div><br>
</div><br>

<button type="button" class="btn btn-danger btn-lg btn-block">
  Please Click to include TAX!&nbsp;&nbsp; <%= form.check_box :tax_inc %>&nbsp;&nbsp;
</button><br>

<% if current_user  && current_user.admin? %>
  <div class="field">
    <font size="5" color="red">Please Update the Actual Cost for this Invoice!</font><br>
    <%= form.text_field :cost, class:'form-control' %>
  </div><br>
<% end %>

<div class="actions">
  <button class="btn btn-info btn-lg btn-block" type="submit"><h2>Proceed to Step #2 to Add Sales Details! </h2></button>
</div>

<% end %>

app/views/layrecs/_reglay.html.erb
<button type="button" class="btn btn-dark btn-lg btn-block">
  <strong>Customer Name:</strong>
  <%= (@layrec.name).titleize %>
  &nbsp;&nbsp; &nbsp;&nbsp;
  <strong>Customer Phone:</strong>
  <%= @layrec.phone %>&nbsp;&nbsp;
  <font size="5" color="red">
    <% if  @layrec.tax_inc == true %>
      <font color="red"><%= number_to_currency lay_tot_reg  %></font>
    <% else %>
      <font color="red"><%= number_to_currency lay_tot  %></font>
    <% end %>
    &nbsp;&nbsp; Invoice Remaining
  </font>
</button>

<div class="container" style= 'background-color: AliceBlue' ><br>
  <div class="row">
    <div class="col-sm">
      <p>
        <strong>Name:</strong>
        <%= @layrec.name.capitalize %>
      </p>

      <p>
        <strong>Phone:</strong>
        <%= @layrec.phone %>
      </p>

      <p>
        <strong>Email:</strong>
        <%= @layrec.email %>
      </p>
      <p>
        <strong>Invoice number:</strong>
        <%= @layrec.phone %>
      </p>
    </div>
    <div class="col-sm">
      <p>
        <strong>Address:</strong>
        <%= @layrec.address.capitalize %>
      </p>

      <p>
        <strong>Address2:</strong>
        <%= @layrec.address2.capitalize %>
      </p>

      <p>
        <strong>City:</strong>
        <%= @layrec.city.capitalize %>
      </p>

    </div>
    <div class="col-sm">
      <p>
        <strong>State:</strong>
        <%= @layrec.state.capitalize %>
      </p>

      <p>
        <strong>Zip:</strong>
        <%= @layrec.zip %>
      </p>
      <p>
        <strong>Date and Time:</strong>
        <%= @layrec.created_at.strftime("%A, %d %b %Y ") %>
      </p>

    </div>
  </div>

  <div class="container" >
    <center>
      <div class="container" style="width: 93%">
        <button type="button" class="btn btn-warning btn-lg btn-block">Purchase Details!</button>
      </div>
      <table class='table table-hover table-striped' style="width: 90%;">
          <thead class='table-dark'>
            <tr>
              <th>QNTY</th>
              <th>Item</th>
              <th>Price</th>
              <th>Description</th>
              <th>Subtotal</th>
              <% if @layrec.tax_inc == true %>
                <th>Tax</th>
              <% end %>
              <th>Action</th>
            </tr>
          </thead>

          <tbody>
            <%  %>
            <% @layrec.goodlays.each do |itm| %>
              <tr>
                <td><%= itm.qny %></td>
                <td><%= number_to_currency itm.price %></td>
                <td><%= itm.item %></td>
                <td><%= itm.discription %></td>
                <% sub_totl = itm.price * itm.qny %>
                <td><%= number_to_currency sub_totl %></td>
                <% if @layrec.tax_inc == true %>
                  <% tax_itm = itm.price * itm.qny * 10.25 / 100%>
                  <td><%= number_to_currency tax_itm %></td>
                  <% else %>
                <% end %>
                <td><%= link_to (image_tag('delx.png',  height: '40px', width: '40px')), [@layrec, itm], method: :delete, data: { confirm: 'You are about delete this item!' } %></td>
              </tr>
            <% end %>
          </tbody>
        </table><hr><br>

        <button type="button" class="btn btn-success btn-lg btn-block">Payments Details History</button>
        <table class='table table-hover table-striped'>
            <thead class='table-dark'>
              <tr>
                <th>SER</th>
                <th>Pyment Method</th>
                <th>Amount</th>
                <th>Sale Rep</th>
                <th>Date</th>
                <% if current_user  && current_user.admin? %>
                  <th>Action</th>
                <% end %>
              </tr>
            </thead>

            <tbody>
              <%  %>
              <% (@layrec.paylays).each_with_index do |pay, index| %>
                <tr>
                  <td><%= index = index + 1 %></td>
                  <td><font size="4" color="green">&nbsp;&nbsp;<%= pay.method %></font></td>
                  <td><%= number_to_currency pay.amount %></td>
                  <td><%= pay.sale_rep %></td>
                  <td><%=  pay.created_at.strftime("%A, %d %b %Y %l:%M %p") %></td>
                  <% if current_user  && current_user.admin? %>
                    <td><%= link_to (image_tag('delx.png',  height: '40px', width: '40px')), [@layrec, pay], method: :delete, data: { confirm: 'You are about delete this item!' } %></td>
                  <% end %>
                </tr>
              <% end %>
            </tbody>
          </table>
          <font size="6" color="green"><%= number_to_currency lay_tot_pay %> Total Payments</font>

          <hr>
      </center>

    <div class="container">
      <div class="row">
        <div class="col-sm">
          <div class="col-sm">
            <button type="button" class="btn btn-success btn-lg btn-block">Delivery Details</button><br>
            <% @layrec.deliverlays.each do |delv| %>
              Delivert Fee: <%= delv.delivery %><br>
              Fee: <%= delv.fee %><br>
              Discount: <%= delv.discount %><br>
              <td><%= link_to (image_tag('delx.png',  height: '40px', width: '40px')), [@layrec, delv], method: :delete, data: { confirm: 'You are about delete this item!' } %></td>
              <hr>
            <% end %>
          </div>

        </div>
        <div class="col-sm">
          <font size="4" color="red"><%= number_to_currency lay_sub_totls %> Items Subtotal</font><br>
          <% if @layrec.tax_inc == true %>
            <font size="4" color="red"><%= number_to_currency lay_tax_calc %> Invoice TAX</font><br>
          <% end %>
          <font size="4" color="red"><%= number_to_currency lay_inv_delivery %> Delivery Fee</font><br>
          <font size="4" color="red"><%= number_to_currency lay_inv_fee   %> Fee If Apply  -</font><br>
          <font size="4" color="blue"><%= number_to_currency lay_inv_dicount  %> Discount If Apply</font><br>
          <hr>
          <% if @layrec.tax_inc == true %>
          <font size="5" color="blue"><%= number_to_currency lay_total_reg %> Invoice Due!</font><br>
          <% else %>
            <font size="5" color="blue"><%= number_to_currency lay_totall %> Invoice Due!</font><br>
          <% end %>
          <font size="5" color="green"><%= number_to_currency lay_tot_pay %> Total Payments</font><br>
          <hr>
          <center>
            <% if lay_tot_reg < 0 %>
              <%= image_tag('x.gif',  height: '90px', width: '90px') %>
              <font size="5" color="red">
              <button type="button" class="btn btn-danger btn-lg btn-block">
                <h4><%= number_to_currency lay_tot_reg %></h4>
              </button>
                 Please Corret this Invoice Remaining</font>
            <% elsif  @layrec.tax_inc == true %>
              <font size="6" color="red"><%= number_to_currency lay_tot_reg  %><br> Invoice Remaining</font>
            <% else %>
              <font size="6" color="red"><%= number_to_currency lay_tot  %><br> Invoice Remaining</font>
            <% end %>
          </center>

        </div>
      </div>
    </div><br>


    <a href="#" id="show_layitems">
      <button type="button" class="btn btn-info btn-lg btn-block"><h3>1- Click to Add Items Details!</h3></button><br>
    </a>
    <div id="layitems" class="hidden">
      <div class="container" style= 'background-color: #F0FFFF'>
        <%= form_for [@layrec, @layrec.goodlays.build] do |f| %>
          <div class="container">
            <div class="row">
              <div class="col-sm">
                <%= f.label :qny %><br>
                <%= f.select :qny, [0,1,2,3,4,5,6,7,8,9,10,11,12] %>
              </div>
              <div class="col-sm">
              <%= f.label :item %>
                <%= f.text_field :item %>
              </div>
              <div class="col-sm">
                <%= f.label :discription %>
                <%= f.text_field :discription %>
              </div>
              <div class="col-sm">
                <%= f.label :price %>
                <%= f.text_field :price %>
              </div>
              <div class="col-sm">
              <%= f.label :vendor %><br>
                <%= f.text_field :vendor %>
              </div>
            </div>

              <div class="col-sm"><br>
                <div class="actions">
                  <button class="btn btn-success btn-lg btn-block " type="submit"><h3> Click here to ADD New Item!</h3></button>
                </div><br>
              </div>
            </div>
          </div>
        <% end %>
      </div><br>

    <a href="#" id="show_laydelivery">
      <button type="button" class="btn btn-info btn-lg btn-block"><h3>2- Click to Add Delivery Details!</h3></button>
    </a><br>
    <div id="laydelivery" class="hidden">
      <div class="container" style= 'background-color: #F0FFFF'><br>
        <%= form_for [@layrec, @layrec.deliverlays.build] do |f| %>
          <div class="row">
            <div class="col">
              <div class="col-sm"><br>
                Delivery Fee: <%= f.text_field :delivery %>
              </div>
            </div>
            <div class="col">
              <div class="col-sm"><br>
                Fee If Apply: <%= f.text_field :fee%>
              </div>
            </div>
            <div class="col">
              <div class="col-sm">
                Discount If Apply: <%= f.text_field :discount %>
              </div>
            </div>
          </div>
          <div class="col-sm"><br>
            <div class="actions">
              <button class="btn btn-success btn-lg btn-block " type="submit"><h3>Click here to ADD Delivery  Details and Discount if Apply!</h3></button>
            </div><br>
          </div>
        <% end %>
      </div><br>
    </div><br><br>

    <a href="#" id="show_laypays">
      <button type="button" class="btn btn-danger btn-lg btn-block"><h2>3- Click to Add Payment Details!</h2></button><br>
    </a>
    <div id="laypays" class="hidden">
      <div class="container" style= 'background-color: #F0FFFF'><br>
        <%= form_for [@layrec, @layrec.paylays.build] do |f| %>
          <div class="row">
            <div class="col">
              <div class="col-sm"><br>
                Amount: <%= f.text_field :amount%>
              </div>
            </div>
            <div class="col">
              <div class="col-sm">

                Method: <%= f.select :method, [ 'SELECT PAYMENT METHOD','Credit', 'Debit', 'Check', ['Cash']] %>
              </div>
            </div>
            <div class="col">
              <div class="col-sm"><br>
              Sale Rep:  <%= f.select :sale_rep,[current_user.username] %>
              </div>
            </div>
          </div>
          <div class="col-sm"><br>
            <div class="actions">
              <button class="btn btn-success btn-lg btn-block " type="submit"><h3> Click here to ADD Payment!</h3></button>
            </div><br>
          </div>
        <% end %>
      </div><br>
    </div><br>
    </div><br>
  </div>
</div>

app/views/layrecs/edit.html.erb
<br>
<button type="button" class="btn btn-primary btn-lg btn-block">Edit Layway Purchase Info </button>

<%= render 'form', layrec: @layrec %><br>

<%= link_to 'See Invoice Details', @layrec, :class => "btn btn-outline-success" %>
<%= link_to 'Back to all Layaway Invoives', layrecs_path, :class => "btn btn-outline-danger" %>

app/views/layrecs/index.html.erb
<div class="row">
  <div class="col-sm">
    <%= link_to 'New Purchase', new_person_path, :class => "btn btn-outline-success btn-lg btn-block" %>
  </div>
  <div class="col-sm">
    <%= link_to 'Sample Invoice', new_exrec_path, :class => "btn btn-outline-danger btn-lg btn-block"  %>
  </div>
  <div class="col-sm">
    <%= link_to 'New Layway Purchase', new_layrec_path, :class => "btn btn-outline-warning btn-lg btn-block"  %>
  </div>
  <div class="col-sm">
    <%= link_to 'All Invoices', people_path, :class => "btn btn-outline-info btn-lg btn-block" %>
  </div>
</div><br>
<button type="button" class="btn btn-info btn-lg btn-block">
  <h3>All Layway Invoices!</h3>
</button>
<center>
  <table id="lay" class="table table-striped table-bordered" style="width: 1000px;">
  <thead class="table-warning">
    <tr>
      <th>Name</th>
      <th>Phone</th>
      <th>Date</th>
      <% if current_user  && current_user.admin? %>
        <th>Action</th>
        <th>Action</th>
      <% end %>
    </tr>
  </thead>

  <tbody>
    <% @layrecs.each do |layrec| %>
      <tr>
        <td><%= link_to layrec.name.titleize, layrec %></td>
        <td><%= layrec.phone %></td>
        <td><%= layrec.created_at.strftime("%A, %d %b %Y") %></td>
        <% if current_user  && current_user.admin? %>
          <td><%= link_to 'Edit', edit_layrec_path(layrec) %></td>
          <td><%= link_to 'Destroy', layrec, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
</center>
<br>

app/views/layrecs/morelay.html.erb
<button type="button" class="btn btn-warning btn-lg btn-block">Layway Payments Details! </button>
<div class="container" style= 'background-color: #F0FFFF'>
  <center>
    <table id="laymore" class="table table-striped table-bordered" style="width: 1000px;">
      <thead class='bg-info'>
        <tr>
          <th>SER</th>
          <th>Method</th>
          <th>Amount</th>
          <th>Sale Rep</th>
          <th>Date</th>
          <th>Customer Phone</th>
          <th>Invoice Due</th>
        </tr>
      </thead>
      <tbody>
        <% laytot = 0 %>
        <% laytot_inv = 0 %>
        <% total_remaining = 0 %>
        <% Paylay.all.each do |pay| %>
        <% laytot += pay.amount%>
        <tr>
          <td><%= pay.id %></td>
          <td><%= pay.method %></td>
          <td><font size="3" color="green"><%= number_to_currency pay.amount %></font></td>
          <td><%= pay.sale_rep%></td>
          <td><%= pay.created_at.strftime("%d %b %Y %l:%M %p")  %></td>
          <td><%= pay.layrec.phone %></td>
          <td><font size="4" color="blue"><%= number_to_currency pay.layrec.total %></font></td>
          <% @rem = (pay.layrec.total - pay.amount) %>
          <% laytot_inv += pay.layrec.total %>
          <% total_remaining += @rem %>
          <% end %>
        </tr>
      </tbody>
    </table>
  </center><br>
  <div class="container">
    <div class="row">
      <div class="col-sm">
        <button type="button" class="btn btn-primary btn-lg btn-block">Total Invoices: <%= number_to_currency laytot_inv %></button>
      </div>
      <div class="col-sm">
        <button type="button" class="btn btn-success btn-lg btn-block">Total Payments: <%= number_to_currency laytot %></button>
      </div>
      <div class="col-sm">
        <button type="button" class="btn btn-outline-danger btn-lg btn-block"><font size="4" color="black">Remaining: <%= number_to_currency total_remaining %> Remaining </font></button>

      </div>
    </div>
  </div><br>
</div><br>
<button type="button" class="btn btn-primary btn-lg btn-block">Daily Sales Count</button><br>
<%= line_chart Layrec.group_by_day(:created_at).count %><br>
<hr>
<button type="button" class="btn btn-primary btn-lg btn-block">Daily Items sales Count</button><br>
<%= line_chart Goodlay.group(:item).group_by_day(:created_at).count %><br>
<div class="container" style= 'background-color: #e6f7ff'>
  <div class="row">
    <div class="col"><br>
      <button type="button" class="btn btn-primary btn-lg btn-block">Sales Rep</button><br>
      <center>
        <%= pie_chart Layrec.group(:sale_rep).count, legend: "bottom", width: "400px", height: "400px" %>
      </center>
    </div>
    <div class="col"><br>
      <button type="button" class="btn btn-primary btn-lg btn-block">Sales Item by Vendor</button><br>
      <center>
        <%= pie_chart Goodlay.group(:vendor).count,  width: "400px", height: "400px" %>
      </center>
    </div>
  </div><br>
</div><br><br>

app/views/layrecs/new.html.erb
<br>
<button type="button" class="btn btn-primary btn-lg btn-block">New Customer Layway Purchase Info </button>

<%= render 'form', layrec: @layrec %>

<%= link_to 'Back to All Layway Invoices!', layrecs_path, :class => "btn btn-outline-success" %>

app/views/layrecs/show.html.erb
<%= link_to "print Recipt (PDF)", layrec_path(@layrec, format: 'pdf'), class:"btn btn-outline-success" %><br><br>
<div class="container" style="width: 93%">
  <button type="button" class="btn btn-warning btn-lg btn-block">
    Layway Purchase
  </button>
</div>
<div class="container" style= 'background-color: #F0FFFF'><br>
<center>
  <% if current_user  && current_user.admin? %>
    <div class='container'>
      <table class='table table-hover table-striped'>
        <thead class='table-dark'>
          <tr>
            <th>Total Invoce</th>
            <th>Sub Total</th>
            <th>Tax</th>
            <th><center>Total Payments</center></th>
            <th>Remaining</th>
            <th>Cost</th>
            <th>Profit</th>
            <th>Margin</th>
          </tr>
        </thead>

        <tbody>
            <tr>
              <td><%= number_to_currency @layrec.total %></td>
              <td><%= number_to_currency @layrec.sub_total %></td>
              <td><%= number_to_currency @layrec.tax %></td>
              <td><center><font size="4" color="green"><%= number_to_currency lay_tot_pay %></font></center></td>
              <% if  @layrec.tax_inc == true %>
                <font color="red"><td><font size="4" color="red"><%= number_to_currency lay_tot_reg %></font></td></font>
              <% else %>
                <td><font size="5" color="red"><%= number_to_currency lay_tot  %></font></td>
              <% end %>
              <td><%= number_to_currency @layrec.cost %></td>
              <td><%= number_to_currency @layrec.profit  %></td>
              <td><%= ( @layrec.profit / @layrec.sub_total * 100).round(2) %> %</td>
            </tr>
        </tbody>
    </table>
    </div>
  <% end %>
</center>
  <%= render 'reglay' %>
  <br>
  <% if current_user  && current_user.admin? %>
    <%= link_to 'Edit Customer Information Only!', edit_layrec_path(@layrec), :class => "btn btn-danger"  %>
  <% end %>
  <%= link_to 'Back to All Layway Invoices!', layrecs_path, :class => "btn btn-outline-success" %><br><br>
</div>