config/routes.rb
Rails.application.routes.draw do
  resources :exrecs do
    resources :exgoods
    resources :exdlvs
  end
  get 'more_info', to: 'people#more'
  get 'delv_info', to: 'delivers#delv'
  get 'more_info_lay', to: 'layrecs#morelay'
  root to:'people#index'
  devise_for :users
  resources :people do
    resources :goods
    resources :pays
    resources :delivers
  end
  resources :layrecs do
    resources :goodlays
    resources :paylays
    resources :deliverlays
  end
end

app/models/exrec.rb
class Exrec < ApplicationRecord
  belongs_to :user
  has_many :exgoods, dependent: :destroy
  has_many :exdlvs, dependent: :destroy
end

app/controllers/exrecs_controller.rb
class ExrecsController < ApplicationController
  before_action :set_exrec, only: [:show, :edit, :update, :destroy]

  def index
    @exrecs = Exrec.all.order("created_at DESC")
  end

  def show
    respond_to do |format|
    format.html
      format.pdf do
        pdf = SamplePdf.new(@exrec, view_context)
        send_data pdf.render, filename: "invoice_#{@exrec.phone}.pdf", type: "application/pdf", disposition: "inline"
      end
    end
  end

  def new
    @exrec = current_user.exrecs.build
  end

  def edit
  end

  def create
    @exrec = current_user.exrecs.build(exrec_params)

    respond_to do |format|
      if @exrec.save
        format.html { redirect_to @exrec, notice: 'Sample Invoice was successfully created.' }
        format.json { render :show, status: :created, location: @exrec }
      else
        format.html { render :new }
        format.json { render json: @exrec.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @exrec.update(exrec_params)
        format.html { redirect_to @exrec, notice: 'Sample Invoice was successfully updated.' }
        format.json { render :show, status: :ok, location: @exrec }
      else
        format.html { render :edit }
        format.json { render json: @exrec.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @exrec.destroy
    respond_to do |format|
      format.html { redirect_to exrecs_url, notice: 'Sample Invoice  was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  def set_exrec
    @exrec = Exrec.find(params[:id])
  end

  def exrec_params
    params.require(:exrec).permit(:name, :phone, :email, :tax_inc, :user_id)
  end
end

app/helpers/exrecs_helper.rb
module ExrecsHelper
  def exsub_totls
    exsub_totls = 0
    @exrec.exgoods.each do |comt|
      exsub_totls += comt.qny * comt.price
    end
    exsub_totls
  end
  def extax_calc
    extax_calc = exsub_totls * 10.25 / 100
  end
  def exinv_dicount
    exinv_dicount = 0
    @exrec.exdlvs.each do |delv|
      exinv_dicount += delv.discount
    end
     exinv_dicount ||= "00.00"
  end
  def exinv_delivery
    exinv_delivery = 0
    @exrec.exdlvs.each do |delv|
      exinv_delivery += delv.delivery
    end
    exinv_delivery ||= "00.00"
  end
  def exinv_fee
      exinv_fee = 0
    @exrec.exdlvs.each do |delv|
       exinv_fee = delv.fee
    end
    exinv_fee
  end
  def extotall
    extotll = (exsub_totls + exinv_fee + exinv_delivery) - exinv_dicount
  end
  def extotall_tax
    extotll = (exsub_totls + exinv_fee + exinv_delivery + extax_calc) - exinv_dicount
  end
end

app/views/exrecs/_form.html.erb
<%= form_with(model: exrec, local: true) do |form| %>
  <% if exrec.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(exrec.errors.count, "error") %> prohibited this exrec from being saved:</h2>

      <ul>
        <% exrec.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="container" style="background-color: #cceeff;" ><br><br>
  <div class="row">
    <div class="col-sm">
      <div class="field">
        <%= form.label :name %>
        <%= form.text_field :name %>
      </div>
    </div>
    <div class="col-sm">
      <div class="field">
        <%= form.label :phone %>
        <%= form.text_field :phone %>
      </div>
    </div>
    <div class="col-sm">
      <div class="field">
        <%= form.label :email %>
        <%= form.text_field :email %>
      </div>
    </div>
  </div><br>
  <button type="button" class="btn btn-primary btn-lg btn-block">
    Check This box to Include TAX!<%= form.check_box :tax_inc %>
  </button>

</div><br>
<div class="actions">
  <button class="btn btn-info btn-lg btn-block" type="submit"><h2>Proceed to Step #2 to Add Sales Details! </h2></button>
</div>
<br>
<% end %>

app/views/exrecs/_sample.html.erb
<center>
  <div class="container" style="width: 93%">
    <button type="button" class="btn btn-warning btn-lg btn-block">Estmate Details!</button>
  </div>
  <table class='table table-hover table-striped' style="width: 90%;">
      <thead class='table-dark'>
        <tr>
          <th>QNTY</th>
          <th>Item</th>
          <th>Price</th>
          <th>Description</th>
          <th>Subtotal</th>
          <% if @exrec.tax_inc == true %>
            <th>Tax</th>
          <% end %>
          <th>Total</th>
          <th>Action</th>
        </tr>
      </thead>

      <tbody>
        <%  %>
        <% @exrec.exgoods.each do |itm| %>
          <tr>
            <td><%= itm.qny %></td>
            <td><%= number_to_currency itm.price %></td>
            <td><%= itm.item %></td>
            <td><%= itm.description %></td>
            <% sub_totl = itm.price * itm.qny %>
            <td><%= number_to_currency sub_totl %></td>
            <% if @exrec.tax_inc == true %>
              <% tax_itm = itm.price * itm.qny * 10.25 / 100%>
              <td><%= number_to_currency tax_itm %></td>
            <% end %>
            <% if @exrec.tax_inc == true %>
              <td><%= number_to_currency sub_totl + tax_itm  %></td>
            <% else %>
              <td><%= number_to_currency sub_totl %></td>
            <% end %>
            <td><%= link_to (image_tag('delx.png',  height: '40px', width: '40px')), [@exrec, itm], method: :delete, data: { confirm: 'You are about delete this item!' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table><hr><br>
  </center>


  <div class="container">
  <div class="row">
    <div class="col-sm">
      <button type="button" class="btn btn-success btn-lg btn-block">Delivery Details</button><br>
      <% @exrec.exdlvs.each do |delv| %>
        Delivert Fee: <%= number_to_currency delv.delivery %><br>
        Fee: <%= number_to_currency delv.fee %><br>
        Discount: <%= number_to_currency delv.discount %>&nbsp;&nbsp;&nbsp;&nbsp;
        <td><%= link_to (image_tag('delx.png',  height: '40px', width: '40px')), [@exrec, delv], method: :delete, data: { confirm: 'You are about delete this item!' } %></td>
        <hr>
      <% end %>
    </div>
    <div class="col-sm">
      <font size="4" color="red"><%= number_to_currency exsub_totls %> Items Subtotal</font><br>
      <% if @exrec.tax_inc == true %>
        <font size="4" color="red"><%= number_to_currency extax_calc %> Invoice TAX</font><br>
      <% end %>
      <font size="4" color="red"><%= number_to_currency exinv_delivery %> Delivery Fee</font><br>
      <font size="4" color="red"><%= number_to_currency exinv_fee   %> Fee If Apply  -</font><br>
      <font size="4" color="blue"><%= number_to_currency exinv_dicount  %> Discount If Apply</font><br>
      <hr>
      <% if @exrec.tax_inc == true %>
        <font size="5" color="red"><%= number_to_currency extotall_tax  %> Invoice Cost</font><br>
      <% else %>
        <font size="5" color="red"><%= number_to_currency extotall  %> Invoice Cost</font><br>
      <% end %>
      <hr>
    </div>
  </div>
  </div><br>


<a href="#" id="show_exitems">
  <button type="button" class="btn btn-info btn-lg btn-block"><h3>1- Click to Add Items Details!</h3></button><br>
</a>
<div id="exitems" class="hidden">
  <div class="container" style= 'background-color: #F0FFFF'>
    <%= form_for [@exrec, @exrec.exgoods.build] do |f| %>
      <div class="container">
        <div class="row">
          <div class="col-sm">
            <%= f.label :qny %><br>
            <%= f.select :qny, [0,1,2,3,4,5,6,7,8,9,10,11,12] %>
          </div>
          <div class="col-sm">
          <%= f.label :item %><br>
            <%= f.text_field :item %>
          </div>
          <div class="col-sm">
            <%= f.label :description %>
            <%= f.text_field :description %>
          </div>
          <div class="col-sm">
            <%= f.label :price %><br>
            <%= f.text_field :price %>
          </div>
        </div>
          <div class="col-sm"><br>
            <div class="actions">
              <button class="btn btn-success btn-lg btn-block " type="submit"><h3> Click here to ADD New Item!</h3></button>
            </div><br>
          </div>
        </div>
      </div>
    <% end %>
  </div><br>


  <a href="#" id="show_dlv">
    <button type="button" class="btn btn-info btn-lg btn-block"><h3>2- Click to Add Delivery Details!</h3></button>
  </a><br>
  <div id="dlv" class="hidden">
    <div class="container" style= 'background-color: #F0FFFF'><br>
      <%= form_for [@exrec, @exrec.exdlvs.build] do |f| %>
        <div class="row">
          <div class="col">
            <div class="col-sm">
              Delivery Fee: <%= f.text_field :delivery %>
            </div>
          </div>
          <div class="col">
            <div class="col-sm">
              Fee If Apply: <%= f.text_field :fee%>
            </div>
          </div>
          <div class="col">
            <div class="col-sm">
              Discoint If Apply: <%= f.text_field :discount %>
            </div>
          </div>
        </div>
        <div class="col-sm"><br>
          <div class="actions">
            <button class="btn btn-success btn-lg btn-block " type="submit"><h3>Click here to ADD Delivery  Details and Discount if Apply!</h3></button>
          </div><br>
        </div>
      <% end %>
    </div><br>
  </div><br><br>

app/views/exrecs/edit.html.erb
<h1>Editing Exrec</h1>

<%= render 'form', exrec: @exrec %>

<%= link_to 'Show', @exrec %> |
<%= link_to 'Back', exrecs_path %>

app/views/exrecs/index.html.erb
<div class="row">
  <div class="col-sm">
    <%= link_to 'New Purchase', new_person_path, :class => "btn btn-outline-success btn-lg btn-block" %>
  </div>
  <div class="col-sm">
    <%= link_to 'Sample Invoice', new_exrec_path, :class => "btn btn-outline-danger btn-lg btn-block"  %>
  </div>
  <div class="col-sm">
    <%= link_to 'New Layway Purchase', new_layrec_path, :class => "btn btn-outline-warning btn-lg btn-block"  %>
  </div>
  <div class="col-sm">
    <%= link_to 'All Layaway Invoices', layrecs_path, :class => "btn btn-outline-info btn-lg btn-block" %>
  </div>
</div><br>
<%= link_to 'New Sample Invoice', new_exrec_path, :class => "btn btn-outline-danger btn-lg btn-block" %><br>

<button type="button" class="btn btn-primary btn-lg btn-block">All Sample Invoices </button><br>
<center>
  <table id="exinv" class="table table-striped table-bordered" style="width: 1000px;" >
  <thead class='table-dark'>
    <tr>
      <th>Name</th>
      <th>Phone</th>
      <th>Email</th>
      <% if current_user  && current_user.admin? %>
        <th>Action</th>
        <th>Action</th>
      <% end %>
    </tr>
  </thead>

  <tbody>
    <% @exrecs.each do |exrec| %>
      <tr>
        <td><%= link_to exrec.name, exrec %></td>
        <td><%= exrec.phone %></td>
        <td><%= exrec.email %></td>
        <% if current_user  && current_user.admin? %>
          <td><%= link_to 'Edit', edit_exrec_path(exrec) %></td>
          <td><%= link_to 'Destroy', exrec, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
</center>

<br>

app/views/exrecs/new.html.erb
<br>
<button type="button" class="btn btn-primary btn-lg btn-block">New Customer Layway Purchase Info </button>
<%= render 'form', exrec: @exrec %>

<%= link_to 'Back', exrecs_path, :class => "btn btn-outline-success" %>

app/views/exrecs/show.html.erb
<%= link_to "print Sample Recipt (PDF)", exrec_path(@exrec, format: 'pdf'), class:"btn btn-outline-success" %><br><br>
<button type="button" class="btn btn-secondary btn-lg btn-block">Sample Invoice</button>
<div class="container" style= 'background-color: #F0FFFF'><br>
  <div class="container"><br>
    <div class="row">
      <div class="col-sm">
        <p>
          <font size="4" color="black">
            <strong>Name:</strong>
            <%= @exrec.name.titleize %>
          </font>
        </p>
      </div>
      <div class="col-sm">
        <p>
          <font size="4" color="black">
            <strong>Phone:</strong>
            <%= @exrec.phone %>
          </font>
        </p>
      </div>
      <div class="col-sm">
        <p>
          <font size="4" color="black">
            <strong>Email:</strong>
            <%= @exrec.email %>
          </font>
        </p>
      </div>
    </div>
  </div><br>

  <%= render 'sample' %>
</div><br>

<% if current_user  && current_user.admin? %>
  <%= link_to 'Edit Customer Information Only!', edit_exrec_path(@exrec), :class => "btn btn-danger"  %>
<% end %>
<%= link_to 'Back to All Invoices!', people_path, :class => "btn btn-outline-success"  %>
</div>