config/routes.rb
Rails.application.routes.draw do
  resources :exrecs do
    resources :exgoods
    resources :exdlvs
  end
  get 'more_info', to: 'people#more'
  get 'delv_info', to: 'delivers#delv'
  get 'more_info_lay', to: 'layrecs#morelay'
  root to:'people#index'
  devise_for :users
  resources :people do
    resources :goods
    resources :pays
    resources :delivers
  end
  resources :layrecs do
    resources :goodlays
    resources :paylays
    resources :deliverlays
  end
end

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-light" style="background-color: #99ccff;">
  <%= link_to (image_tag('drapplogo.png',  height: '50px', width: '160px')) , people_path %>&nbsp;&nbsp;
  <form class="form-inline my-2 my-lg-0">
  <% if current_user  && current_user.admin? %>
  <%= link_to 'Delivery', delv_info_path , :class => "btn btn-outline-danger"%>&nbsp;&nbsp;
    <%= link_to 'Sales', more_info_path, :class => "btn btn-outline-danger"%>&nbsp;&nbsp;
    <%= link_to 'Layaway', more_info_lay_path, :class => "btn btn-outline-danger"%>&nbsp;&nbsp;
  <% end %>
  <% if user_signed_in? %>
    <button type="button" class="btn btn-primary">
      Rep Name <span class="badge badge-light"><%= current_user.username %></span>
      <span class="sr-only">unread messages</span>
    </button>&nbsp;&nbsp;

    <%= link_to 'Edit profile', edit_user_registration_path, :class => "btn btn-outline-primary"%>&nbsp;&nbsp;

    <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => "btn btn-outline-primary"  %>
  <% else %>
    <%= link_to "Sign up", new_user_registration_path, :class => "btn btn-outline-primary"  %>&nbsp;&nbsp;
    <%= link_to "Login", new_user_session_path, :class => "btn btn-outline-primary" %>
  <% end %>
  </form>
</nav>
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>">
    <a href="#" data-dismiss="alert" class="close">×</a>
    <ul>
      <li>
        <%= value %>
      </li>
    </ul>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<div class="pos-f-t">
  <div class="collapse" id="navbarToggleExternalContent">
    <div class="bg-dark p-4">
      <h5 class="text-white h4">Collapsed content</h5>
      <span class="text-muted">Toggleable via the navbar brand.</span>
    </div>
  </div>
  <nav class="navbar navbar-dark bg-dark">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggleExternalContent" aria-controls="navbarToggleExternalContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mngdr2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= render 'layouts/nav' %><br>
      <%= yield %>
    </div>
  </body>
</html>